name: CMake-MacOS

on:
  push:
  pull_request:
  schedule:
    - cron: '40 5 * * *'
    
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run:  brew install sfml gmp
      
    - name: Configure CMake
      working-directory: ./src
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ./src
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose -C ${{env.BUILD_TYPE}}
